version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - event-radar-network

  kafka:
  image: confluentinc/cp-kafka:7.5.1
  ports:
    - "9092:9092"
  environment:
    KAFKA_BROKER_ID: 1
    KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
    KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
    KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  depends_on:
    - zookeeper
  networks:
    - event-radar-network

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - event-radar-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - kafka
      - redis
    networks:
      - event-radar-network

  frontend:
    environment:
      - REACT_APP_API_URL=http://158.179.216.162:5000
    build: ./frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - event-radar-network
    env_file:
      - ./frontend/.env

networks:
  event-radar-network:
    driver: bridge
